[Variables]
;Color used for large horizontal and vertical indicators
Clr.VLine=#LineColor1#
Clr.HLine=#LineColor2#

;===== Positioning options =====
;Cell Dimensions - The dimensions of the individual string meters.
C.w=(10*#Scale#)
C.h=(10*#Scale#)
;Spacers and bumper
;Vertical space between cells
Space.x=(6*#Scale#)
;Horizontal space between cells
Space.y=(2*#Scale#)
;Space on left and right of calendar
Bumper.x=(24*#Scale#)
;Space on top of calendar
Bumper.top=(12*#Scale#)
;Space on bottom of calendar
Bumper.bottom=(0*#Scale#)