;------------------THROBBER-----------------------------

[Throbber1]
Meter=Shape
X=(5*#APPBARSCALE#)
Y=(5*#APPBARSCALE#)
Shape=Rectangle (0*#APPBARSCALE#),(0*#APPBARSCALE#),(5*#APPBARSCALE#),(5*#APPBARSCALE#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor1#

[Throbber2]
Meter=Shape
X=(5*#APPBARSCALE#)
Y=(15*#APPBARSCALE#)
Shape=Rectangle (0*#APPBARSCALE#),(0*#APPBARSCALE#),(5*#APPBARSCALE#),(5*#APPBARSCALE#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor2#

[Throbber3]
Meter=Shape
X=(5*#APPBARSCALE#)
Y=(25*#APPBARSCALE#)
Shape=Rectangle (0*#APPBARSCALE#),(0*#APPBARSCALE#),(5*#APPBARSCALE#),(5*#APPBARSCALE#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor3#

