;------------------THROBBER-----------------------------

[Throbber1]
Meter=Shape
X=(5*#APPGADGETSCALE#)
Y=(5*#APPGADGETSCALE#)
Shape=Rectangle (0*#APPGADGETSCALE#),(0*#APPGADGETSCALE#),(5*#APPGADGETSCALE#),(5*#APPGADGETSCALE#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor1#

[Throbber2]
Meter=Shape
X=(5*#APPGADGETSCALE#)
Y=(15*#APPGADGETSCALE#)
Shape=Rectangle (0*#APPGADGETSCALE#),(0*#APPGADGETSCALE#),(5*#APPGADGETSCALE#),(5*#APPGADGETSCALE#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor2#

[Throbber3]
Meter=Shape
X=(5*#APPGADGETSCALE#)
Y=(25*#APPGADGETSCALE#)
Shape=Rectangle (0*#APPGADGETSCALE#),(0*#APPGADGETSCALE#),(5*#APPGADGETSCALE#),(5*#APPGADGETSCALE#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor3#

