;------------------THROBBER-----------------------------

[Throbber1]
Meter=Shape
X=5
Y=5
;MyFillGradient=0,0 | #PaletteColor1# ; 0.3 | #PaletteColor2# ; 1.0
Shape=Rectangle 0,0,5,5,50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor1#

[Throbber2]
Meter=Shape
X=15
Y=5
;MyFillGradient=0,0 | #PaletteColor2# ; 0.3 | #PaletteColor3# ; 1.0
Shape=Rectangle 0,0,5,5,50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor2#

[Throbber3]
Meter=Shape
X=25
Y=5
;MyFillGradient=0,0 | #PaletteColor3# ; 0.3 | #PaletteColor1# ; 1.0
Shape=Rectangle 0,0,5,5,50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor3#
