;------------------THROBBER-----------------------------

[Throbber1]
Meter=Shape
X=(5*#Scale#)
Y=(5*#Scale#)
Shape=Rectangle (0*#Scale#),(0*#Scale#),(5*#Scale#),(5*#Scale#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor1#

[Throbber2]
Meter=Shape
X=(5*#Scale#)
Y=(15*#Scale#)
Shape=Rectangle (0*#Scale#),(0*#Scale#),(5*#Scale#),(5*#Scale#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor2#

[Throbber3]
Meter=Shape
X=(5*#Scale#)
Y=(25*#Scale#)
Shape=Rectangle (0*#Scale#),(0*#Scale#),(5*#Scale#),(5*#Scale#),50 | StrokeWidth  0 | Stroke Color #StrokeMainColor# | Fill Color #PaletteColor3#

