;///////////////////////////////////////////////////////////////////////////////////////////////////
;                                    Top Process Meter Settings
;///////////////////////////////////////////////////////////////////////////////////////////////////

[Variables]
; background
dBgAlpha=255
dBgStyle=0

; font appearance
dColorFontTitle=255,255,255
dColorFontSubtitle=78,127,191
dColorFontSubtitle2=255,246,42
dColorInfoText1=237,231,216
dColorInfoText2=201,205,209

; color palette
dPaletteColor1=107,238,98
dPaletteColor2=255,246,42
dPaletteColor3=250,158,0
dPaletteColor4=236,28,70
dPaletteColor5=199,36,199
dPaletteColor6=145,70,232
dPaletteColor7=42,112,250
dPaletteColor8=43,224,224
dPaletteColor9=121,182,62
dPaletteColor10=204,255,0
dPaletteColor11=250,205,22
dPaletteColor12=191,100,55
dPaletteColor13=201,41,56
dPaletteColor14=179,0,91
dPaletteColor15=153,84,166
dPaletteColor16=99,125,217