[Variables]

;=====================|   WEATHER   |=====================

LocationCode=

TempSymbol=C
MeasureName2=MeasureTempCelsius

;=====================|   APP VOLUME EXCLUDED   |====================

VOLUMEEXCLUDED=rainmeter.exe;Discord.exe;steam.exe

;=====================|   APPBAR VIEW   |=====================

AppPath1=C:\Users\steve\Documents\Shortcuts\Applications\
AppPath2=C:\Users\steve\Documents\Shortcuts\Games\
AppPath3=C:\Users\steve\Downloads\


;=====================|   HDDS   |====================

Drive1=C
Drive2=D
Drive3=E
Drive4=F
Drive5=G
Drive6=B
Drive7=S
Drive8=
Drive9=

;=====================|   NET   |====================

MaxDownloadMbits=100
MaxUploadMbits=7

Interface=Best

;=====================|   MUSIC PLAYER   |====================

PLAYERNAME=Spotify

;=====================|   HWINFO   |====================

HWINFO1=ValueRaw14
HWINFO2=ValueRaw1
HWINFO3=ValueRaw2
HWINFO4=ValueRaw3
HWINFO5=ValueRaw5
HWINFO6=ValueRaw6
HWINFO7=ValueRaw7
HWINFO8=ValueRaw8
HWINFO9=ValueRaw9
HWINFO10=ValueRaw10
HWINFO11=ValueRaw11
HWINFO12=ValueRaw12
HWINFO13=ValueRaw13
HWINFO14=ValueRaw18
HWINFO15=ValueRaw4
HWINFO16=ValueRaw14
HWINFO17=ValueRaw15
HWINFO18=ValueRaw16
HWINFO19=ValueRaw17
HWINFO20=Value19
HWINFO21=Value21
HWINFO22=Value22
HWINFO23=ValueRaw20

;=====================|   FANS   |====================

FAN1=2000
FAN2=1500
FAN3=2000
FAN4=2000

;=====================|   SCALING   |====================
ScrollMouseIncrement=0.5
