[Variables]
 AppName1=Mozilla Firefox
 AppIcon1=#@#Images\120.ico
 AppPath1=
 ;---------------------------
 AppName2=Internet Explorer
 AppIcon2=#@#Images\Content\IE.png
 AppPath2=iexplore.exe
 ;---------------------------
 AppName3=Microsoft Word
 AppIcon3=#@#Images\Content\Word.png
 AppPath3=winword.exe
 ;---------------------------
 AppName4=Microsoft Excel
 AppIcon4=#@#Images\Content\Excel.png
 AppPath4=excel.exe
 ;---------------------------
 AppName5=VLC Media Player
 AppIcon5=#@#Images\Content\VLC.png
 AppPath5=C:\Program Files\VideoLAN\VLC\vlc.exe
 ;---------------------------
 AppName6=Windows Media Player
 AppIcon6=#@#Images\Content\WMP.png
 AppPath6=wmplayer.exe
 ;---------------------------
 AppName7=Adobe Illustrator
 AppIcon7=#@#Images\Content\Illustrator.png
 AppPath7=
 ;---------------------------
 AppName8=Adobe Dreamweaver
 AppIcon8=#@#Images\Content\Dreamweaver.png
 AppPath8=
 ;---------------------------
 AppName9=Adobe Photoshop
 AppIcon9=#@#Images\Content\Photoshop.png
 AppPath9=
 ;---------------------------
 AppName10=uTorrent
 AppIcon10=#@#Images\Content\uTorrent.png
 AppPath10=
 ;---------------------------
 AppName11=Calculator
 AppIcon11=#@#Images\Content\Calculator.png
 AppPath11=Calc.exe